SELECT sum(CSTMR_ID) as CSTMR_ID,DW_PRCSS_ID,ADDR_TYPE FROM delta.`/mnt/silver/WAREHOUSE/ADMIN/CUSTOMER_ADDRESS/` GROUP BY DW_PRCSS_ID,ADDR_TYPE ORDER BY DW_PRCSS_ID
SELECT sum(CSTMR_ID) as CSTMR_ID,DW_PRCSS_ID,ADDR_TYPE FROM WAREHOUSE..CUSTOMER_ADDRESS GROUP BY DW_PRCSS_ID,ADDR_TYPE ORDER BY DW_PRCSS_ID


select sum(PRCNT_MATCH_CNFDNC) as PRCNT_MATCH_CNFDNC,CSTMR_STORE_NUMBER from WAREHOUSE..CUSTOMER 
GROUP BY PRCNT_MATCH_CNFDNC,CSTMR_STORE_NUMBER

SELECT ADDR_SOURCE, count(DW_PRCSS_ID) FROM WAREHOUSE..EMAIL_ADDRESS GROUP BY ADDR_SOURCE

select * from WAREHOUSE..EMAIL_ADDRESS where ADDR_SOURCE = 16

SELECT  sum(ADDR_SOURCE) as ADDR_SOURCE,DW_PRCSS_ID,ADDR_TYPE FROM WAREHOUSE..EMAIL_ADDRESS GROUP BY DW_PRCSS_ID,ADDR_TYPE ORDER BY DW_PRCSS_ID

select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..PHONE_NUMBER group by to_char(EFFCTV_DATE, 'yyyy MMM')

select * from WAREHOUSE..PHONE_NUMBER where to_char(EFFCTV_DATE, 'yyyy MMM') = '2011 12M'

SELECT  sum(ADDR_SOURCE) as ADDR_SOURCE,DW_PRCSS_ID,ADDR_TYPE FROM WAREHOUSE..PHONE_NUMBER GROUP BY DW_PRCSS_ID,ADDR_TYPE

select to_char(CSTMR_ACCNT_MODIFY_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..CUSTOMER_ACCOUNT group by to_char(CSTMR_ACCNT_MODIFY_DATE, 'yyyy MMM')

select to_char(CSTMR_ACCNT_MODIFY_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..CUSTOMER_ACCOUNT group by to_char(CSTMR_ACCNT_MODIFY_DATE, 'yyyy MMM')

SELECT  to_char(CSTMR_ACCNT_CREATE_DATE, 'yyyy MMM'), count(*) FROM GDC_WAREHOUSE.ADMIN.CUSTOMER_ACCOUNT GROUP BY to_char(CSTMR_ACCNT_CREATE_DATE, 'yyyy MMM')

select * from WAREHOUSE..CUSTOMER_ACCOUNT where to_char(CSTMR_ACCNT_MODIFY_DATE, 'yyyy MMM') = '2011 11M'

SELECT sum(CSTMR_SOURCE) as CSTMR_SOURCE,DW_PRCSS_ID,CSTMR_ACCNT_STATUS_CODE FROM WAREHOUSE..CUSTOMER_ACCOUNT GROUP BY DW_PRCSS_ID,CSTMR_ACCNT_STATUS_CODE

select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..PHONE_NUMBER_HIST group by to_char(EFFCTV_DATE, 'yyyy MMM')

select * from WAREHOUSE..PHONE_NUMBER_HIST where to_char(EFFCTV_DATE, 'yyyy MMM') = '2013 12M'

SELECT sum(ADDR_SOURCE) as ADDR_SOURCE,DW_PRCSS_ID,ADDR_TYPE FROM WAREHOUSE..PHONE_NUMBER_HIST GROUP BY DW_PRCSS_ID,ADDR_TYPE


SELECT sum(CSTMR_SOURCE) as CSTMR_SOURCE,DW_PRCSS_ID FROM WAREHOUSE..CUSTOMER_ACCOUNT_HIST GROUP BY DW_PRCSS_ID

select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..CUSTOMER_ADDRESS_HIST group by to_char(EFFCTV_DATE, 'yyyy MMM')
select * from WAREHOUSE..CUSTOMER_ADDRESS_HIST where to_char(EFFCTV_DATE, 'yyyy MMM') = '2013 07M'
SELECT sum(CSTMR_ID) as CSTMR_ID,DW_PRCSS_ID FROM WAREHOUSE..CUSTOMER_ADDRESS_HIST GROUP BY DW_PRCSS_ID

select * from WAREHOUSE..CUSTOMER_HIST where to_char(CSTMR_FIRST_VISIT_DATE, 'yyyy MMM') = '2003 02M'
select to_char(CSTMR_FIRST_VISIT_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..CUSTOMER_HIST group by to_char(CSTMR_FIRST_VISIT_DATE, 'yyyy MMM')
SELECT sum(CSTMR_SOURCE) as CSTMR_SOURCE,DW_PRCSS_ID FROM WAREHOUSE..CUSTOMER_HIST GROUP BY DW_PRCSS_ID

SELECT sum(ADDR_SOURCE) as ADDR_SOURCE,ADDR_ID FROM WAREHOUSE..EMAIL_ADDRESS_HIST GROUP BY ADDR_ID
select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..EMAIL_ADDRESS_HIST group by to_char(EFFCTV_DATE, 'yyyy MMM')
select * from WAREHOUSE..EMAIL_ADDRESS_HIST where to_char(EFFCTV_DATE, 'yyyy MMM') = '2010 08M'

select to_char(RGSTRD_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..CUSTOMER_REGISTRATION group by to_char(RGSTRD_DATE, 'yyyy MMM')
select * from WAREHOUSE..CUSTOMER_REGISTRATION where to_char(RGSTRD_DATE, 'yyyy MMM') = '2017 11M'
SELECT sum(CSTMR_RGSTRD_SOURCE) as CSTMR_RGSTRD_SOURCE,HR_ID FROM WAREHOUSE..CUSTOMER_REGISTRATION GROUP BY HR_ID

select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..ADDRESS_HIST group by to_char(EFFCTV_DATE, 'yyyy MMM')
select * from WAREHOUSE..ADDRESS_HIST where to_char(EFFCTV_DATE, 'yyyy MMM') = '2023 05M'
SELECT sum(DW_PRCSS_ID) as DW_PRCSS_ID,ADDR_ID FROM WAREHOUSE..ADDRESS_HIST GROUP BY ADDR_ID

select to_char(TIMESTAMP, 'yyyy MMM'),count(*) from  HYBRIS..HYM_INTERACTIONS_CAMPAIGN_HISTORY group by  to_char(TIMESTAMP, 'yyyy MMM')
select count(*) from  HYBRIS_DR..HYM_INTERACTIONS_CAMPAIGN_HISTORY where to_char(TIMESTAMP,'yyyy MMM') ='2017 Apr'

select to_char(EFFCTV_DATE, 'yyyy MMM'), count(*) from WAREHOUSE..DNC_CUSTOMER_COMMUNICATION group by to_char(EFFCTV_DATE, 'yyyy MMM')
select * from WAREHOUSE..DNC_CUSTOMER_COMMUNICATION where to_char(EFFCTV_DATE, 'yyyy MMM') = '2018 01M'
SELECT sum(DW_PRCSS_ID) as DW_PRCSS_ID,ENTITY_ID FROM WAREHOUSE..DNC_CUSTOMER_COMMUNICATION GROUP BY ENTITY_ID

select to_char(OPTOUT_DATETIME, 'YYYY MMM'), count(*) from HYBRIS..HYM_EMAIL_OPTOUT group by to_char(OPTOUT_DATETIME, 'YYYY MMM')
select * from HYBRIS..HYM_EMAIL_OPTOUT where to_char(OPTOUT_DATETIME, 'yyyy MMM') = '2017 01M'
SELECT sum(EMAIL_OPTOUT_ID) as EMAIL_OPTOUT_ID,HY_PROCESS_ID,ENTITY_ID FROM HYBRIS..HYM_EMAIL_OPTOUT GROUP BY HY_PROCESS_ID,ENTITY_ID

select to_char(TIMESTAMP, 'yyyy MMM'),count(*) from  HYBRIS_DR..HYM_INTERACTIONS_APPOINTMENT group by  to_char(TIMESTAMP, 'yyyy MMM')
select sum(AMOUNT) as AMOUNT, to_char(TIMESTAMP, 'yyyy MMM') as TIMESTAMP from HYBRIS_DR..HYM_INTERACTIONS_APPOINTMENT_HIST group by to_char(TIMESTAMP, 'yyyy MMM')
select * from  HYBRIS_DR..HYM_INTERACTIONS_CAMPAIGN_HISTORY where to_char(TIMESTAMP,'yyyy MMM') ='2017 Apr'

select to_char(TICKET_ORDER_DATE, 'yyyy Mon'),count(*) from HYBRIS..HYM_INTERACTIONS_TICKET_HIST group by to_char(TICKET_ORDER_DATE, 'yyyy Mon')
select * from  HYBRIS..HYM_INTERACTIONS_TICKET_HIST where to_char(TICKET_ORDER_DATE,'yyyy Mon') ='2017 Apr'
select sum(AMOUNT) as AMOUNT, to_char(TICKET_ORDER_DATE, 'yyyy Mon') as TICKET_ORDER_DATE from HYBRIS..HYM_INTERACTIONS_TICKET_HIST group by to_char(TICKET_ORDER_DATE, 'yyyy Mon')

select to_char(INVC_TS, 'yyyy Mon'),count(*) from MART..DIM_INVOICE group by to_char(INVC_TS, 'yyyy Mon')
select * from  from MART..DIM_INVOICE where to_char(TICKET_ORDER_DATE,'yyyy Mon') ='2017 Apr'
select sum(INVC_MC_AMT) as AMOUNT, to_char(INVC_TS, 'yyyy Mon') as TICKET_ORDER_DATE from MART..DIM_INVOICE group by to_char(INVC_TS, 'yyyy Mon')

